### ISSUE TITLE
Ability to define set of files to copy.

### ISSUE THREAD

**Issue by knyttl** [tcurdt/jdeb#111]
At the moment, when you want to copy three files within `dataSet` section, you need to define three sections `<data>`: https://gist.github.com/knyttl/75ad5d55f49517a11a5d

It would be great if this could be simplified, for instance as follows: https://gist.github.com/knyttl/aa11a068599321c3feb9

**Comment by tcurdt** [comment]
> Since there are many dependencies, it's really painful to copy-and-paste several lines of xml for every dependency to only replace a single line. Such a way is not acceptable for me.

Not to beat a dead horse - but a much better approach would be bundle the dependencies into a single jar. The maven shade plugin is great for that.
