### ISSUE TITLE
Possible issue with different encodes

### ISSUE THREAD

**Issue by spinscale** [tcurdt/jdeb#155]
Hey,

I have the following in my `pom.xml`

```
...
                                <data>
                                    <src>${project.basedir}/src/deb/default/</src>
                                    <type>directory</type>
                                    <excludes>.DS_Store</excludes>
                                    <mapper>
                                        <type>perm</type>
                                        <prefix>/etc/default</prefix>
                                        <user>root</user>
                                        <group>root</group>
                                    </mapper>
                                </data>
...
```

There is only one file inside which is in unix encoding. However, when the packaging is done under windows, this file suddenly gets converted to windows `line.separators`, which then makes it uninstallable under debian linux, as the it cannot be sourced anymore and bash returns and error code which in turn stops the installation. Also this does not seem to happen with every windows installation (works on two other machines).

I have only taken a quick peek at the source, but I thought the specified files are simply copied and not changed in any way (or is this possible with the template functionality)? Anything else which could cause this behaviour?

Any hints are greatly appreciated.

**Comment by tombrown52** [comment]
I have an issue that sounds like this one. My entire repository is checked out from git with windows line endings. When jdeb builds the control.tar it correctly converts all control scripts from windows to unix line endings. But any scripts packaged in data.tar retain the windows line endings (no detection or conversion is done, the resources are opened simply with FileInputStream; https://github.com/tcurdt/jdeb/blob/master/src/main/java/org/vafer/jdeb/producers/AbstractDataProducer.java#L87). How can I package scripts that are not control scripts?

**Comment by tcurdt** [comment]
@tombrown52 at this jdeb does not support file conversion like that.

Either [use git for this](https://help.github.com/articles/dealing-with-line-endings/) or (if the files are not changing that often) just tar them up and use those as input.

Feel free to add it as feature request for version 2 though https://github.com/tcurdt/jdeb/issues/195

**Comment by tombrown52** [comment]
For others who stumble on this, I have solved it by running dos2unix on my data sh files via the postinst control script. I also declare dos2unix as a dependency to ensure it's present. A little ugly, but it works no matter how the line endings are or which system builds the .deb.

**Comment by tcurdt** [comment]
Really not the recommended way - but if it works for you... so be it.

**Comment by tombrown52** [comment]
I think in this case git is not the best tool to use for changing the line endings. They're text files; Having git treat them as binary, while functional, is technically incorrect. It also requires each contributor to correctly set line endings in their editor.

Is the tar file solution you suggest automated (e.g. using the assembly plugin), or are you suggesting manually creating a tar with .sh scripts?

**Comment by tcurdt** [comment]
@tombrown52 I recommend re-reading the article I linked. No one said they should be treated as binary. Using `*.sh text eol=lf` is indeed technical and functional correct.
