### ISSUE TITLE
Inconsistency in md5sums file

### ISSUE THREAD

**Issue by peternewman** [tcurdt/jdeb#169]
I noticed something curious about the md5sums file generated by jdeb, all the files listed have a preceding ./, like so:
8bc944dbd052ef51652e70a5104492e3  ./test/testfile

In comparison, anything generated in a normal deb looks like this:
8bc944dbd052ef51652e70a5104492e3  test/testfile

If you run this:
grep "\.\/" /var/lib/dpkg/info/*.md5sums

Then I believe the only files returned will be debs generated by jdeb.

It doesn't seem to affect "md5sum -c", or the other few bits I've tried, but worth flagging up for consideration and possible fixing.

**Comment by tcurdt** [comment]
This is related to https://github.com/tcurdt/jdeb/issues/217 We'll track this over there.
