### ISSUE TITLE
Disc C: is added to the install directory

### ISSUE THREAD

**Issue by annabekkerman** [tcurdt/jdeb#185]
I'm setting the install directory to /var/lib/tomcat6/webapps in the plugin configuration section but for some reason a disc C: is added to it so that the final path looks like this: C_\var\lib\tomcat6\webapps. Why is this happening and how can I fix this?

Here's the relevant snippet from the pom.xml:

```xml
<plugin>
      	<artifactId>jdeb</artifactId>
      	<groupId>org.vafer</groupId>
      	<version>1.3</version>
      	<executions>
        	<execution>
        		<phase>package</phase>
        		<goals>
        		    <goal>jdeb</goal>
          		</goals>
          		<configuration>
          			<installDir>/var/lib/tomcat6/webapps</installDir>
          		</configuration>
        		</execution>
      	</executions>
</plugin>
```

**Comment by tcurdt** [comment]
This is on windows I guess?

**Comment by tcurdt** [comment]
@ebourg didn't you have a windows box? could you confirm whether this is a real problem or not?

**Comment by tcurdt** [comment]
@annabekkerman any progress on this? or can this issue be closed?

**Comment by tcurdt** [comment]
no feedback, no way to reproduce it - closing
