### ISSUE TITLE
Directory permissions

### ISSUE THREAD

**Issue by sirsquall** [tcurdt/jdeb#193]
Hi,

I'm tryng to set a permission on a directory like this: 

```xml
<data>
  <src>${project.basedir}/app/files</src>
  <type>directory</type>
  <mapper>
    <type>perm</type>
    <prefix>${deb.base.dir}/app/files</prefix>
    <user>www-data</user>
    <group>www-data</group>
    <filemode>775</filemode>
    <dirmode>775</dirmode>
  </mapper>
</data>
````
And the directory "files" have the permission 755 and not 775.

I don't know what I'm doing wrong, if someone have an idea ?

**Comment by muuki88** [comment]
What solved the problem?

**Comment by sirsquall** [comment]
Before this statment, I had another for the all app directory.
So I splited all the directories, and setted all the perms correctly
