### ISSUE TITLE
changelog-file-missing-in-native-package

### ISSUE THREAD

**Issue by cdanger** [tcurdt/jdeb#198]
Hello,
I have the following errors when checking my jdeb-generated debian package with lintian:
changelog-file-missing-in-native-package
no-copyright-file

(I already have the contents of debian/changelog and debian/copyright ready.) 
Could you tell me where to put the changelog and copyright files in the maven project and if any specific jdeb configuration is necessary to handle these files?
I am using jdeb 1.4 and my "controlDir" is "src/debian/control" if this is of any help.

Thanks for your support.

**Comment by tcurdt** [comment]
Well, it says https://lintian.debian.org/tags/changelog-file-missing-in-native-package.html

> Each Debian package (which provides a /usr/share/doc/pkg directory) has to install a changelog file. ..., the file should usually be installed as /usr/share/doc/pkg/changelog.gz
> 
> Note that Lintian may emit this tag if the changelog exists, but it does not look like a Debian changelog.

Which I read as if you have to have a file at `/usr/share/doc/pkg/changelog.gz` (or possibly `/usr/share/doc/pkg/changelog`) - be it empty or not.  But only if you have a `/usr/share/doc/pkg`.

So you could create a new `data` section and map your file changelog accordingly into that location.

For the copyright see https://lintian.debian.org/tags/no-copyright-file.html

**Comment by cdanger** [comment]
OK. I used a data section as you suggested. Now I have a new complaint from lintian:
changelog-file-not-compressed changelog
... which is already addressed by issue #157 
So I can close this ticket. Thanks for your help.
