### ISSUE TITLE
missing dependency on org.codehaus.plexus:plexus-utils:1.5.2

### ISSUE THREAD

**Issue by infothrill** [tcurdt/jdeb#205]
Because jdeb does not declare an explicit dependency on

        <dependency>
        	<groupId>org.codehaus.plexus</groupId>
        	<artifactId>plexus-utils</artifactId>
        	<version>[1.5.2,)</version>
        </dependency>

, the call to org.codehaus.plexus.util.StringUtils.isBlank might fail in setups where the automatic dependency resolution decides to pull in an older version than 1.5.2:

    [FATAL ERROR] org.vafer.jdeb.maven.DebMojo#execute() caused a linkage error (java.lang.NoSuchMethodError) and may be out-of-date. Check the realms:
    [FATAL ERROR] Plugin realm = app0.child-container[org.vafer:jdeb:1.4]
    ...
    urls[4] = file:/var/lib/jenkins/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
    ...
    [FATAL ERROR] Container realm = plexus.core.maven
    ...
    urls[5] = file:/var/lib/jenkins/.m2/repository/org/codehaus/plexus/plexus-utils/1.1/plexus-utils-1.1.jar
    ...
    [INFO] Trace
    java.lang.NoSuchMethodError: org.codehaus.plexus.util.StringUtils.isBlank(Ljava/lang/String;)Z
    ...

The dependency is currently missing and on fresh build environments, things seem to work fine (probably because of transitive dependencies and fresh .m2 caches with new versions).

**Comment by tmortagne** [comment]
It would indeed be cleaner to have a direct dependency on plexus-utils since jdeb directly use it. Now I prefer using 3.0.20 for the version since that's what maven-core triggers right now.

Now dealing with conflicts coming from one of your dependencies is not really jdeb's job and you should probably use <dependencyManagement> or put your dependencies in the right order to be safe.

**Comment by tcurdt** [comment]
OMG we are using `org.codehaus.plexus.util.StringUtils.isBlank` directly?
We should fix that - and not add the dependency.

Maybe it would be good if we could upgrade some deps to get rid of the conflicts though.

    org.vafer:jdeb:maven-plugin:1.4
    +- commons-io:commons-io:jar:2.4:compile
    +- org.apache.commons:commons-compress:jar:1.8:compile
    |  \- org.tukaani:xz:jar:1.5:compile
    +- org.apache.maven:maven-core:jar:3.2.5:compile
    |  +- org.apache.maven:maven-model:jar:3.2.5:compile
    |  |  \- (org.codehaus.plexus:plexus-utils:jar:3.0.20:compile - omitted for duplicate)
    |  +- org.apache.maven:maven-settings:jar:3.2.5:compile
    |  |  \- (org.codehaus.plexus:plexus-utils:jar:3.0.20:compile - omitted for duplicate)
    |  +- org.apache.maven:maven-settings-builder:jar:3.2.5:compile
    |  |  +- (org.codehaus.plexus:plexus-utils:jar:3.0.20:compile - omitted for duplicate)
    |  |  +- (org.codehaus.plexus:plexus-interpolation:jar:1.21:compile - omitted for duplicate)
    |  |  +- (org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile - omitted for duplicate)
    |  |  +- (org.apache.maven:maven-settings:jar:3.2.5:compile - omitted for duplicate)
    |  |  \- (org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile - omitted for duplicate)
    |  +- org.apache.maven:maven-repository-metadata:jar:3.2.5:compile
    |  |  \- (org.codehaus.plexus:plexus-utils:jar:3.0.20:compile - omitted for duplicate)
    |  +- org.apache.maven:maven-artifact:jar:3.2.5:compile
    |  |  \- (org.codehaus.plexus:plexus-utils:jar:3.0.20:compile - omitted for duplicate)
    |  +- (org.apache.maven:maven-plugin-api:jar:3.2.5:compile - omitted for duplicate)
    |  +- org.apache.maven:maven-model-builder:jar:3.2.5:compile
    |  |  +- (org.codehaus.plexus:plexus-utils:jar:3.0.20:compile - omitted for duplicate)
    |  |  +- (org.codehaus.plexus:plexus-interpolation:jar:1.21:compile - omitted for duplicate)
    |  |  +- (org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile - omitted for duplicate)
    |  |  \- (org.apache.maven:maven-model:jar:3.2.5:compile - omitted for duplicate)
    |  +- org.apache.maven:maven-aether-provider:jar:3.2.5:compile
    |  |  +- (org.apache.maven:maven-model:jar:3.2.5:compile - omitted for duplicate)
    |  |  +- (org.apache.maven:maven-model-builder:jar:3.2.5:compile - omitted for duplicate)
    |  |  +- (org.apache.maven:maven-repository-metadata:jar:3.2.5:compile - omitted for duplicate)
    |  |  +- (org.eclipse.aether:aether-api:jar:1.0.0.v20140518:compile - omitted for duplicate)
    |  |  +- org.eclipse.aether:aether-spi:jar:1.0.0.v20140518:compile
    |  |  |  \- (org.eclipse.aether:aether-api:jar:1.0.0.v20140518:compile - omitted for duplicate)
    |  |  +- (org.eclipse.aether:aether-util:jar:1.0.0.v20140518:compile - omitted for duplicate)
    |  |  +- (org.eclipse.aether:aether-impl:jar:1.0.0.v20140518:compile - omitted for duplicate)
    |  |  +- (org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile - omitted for duplicate)
    |  |  \- (org.codehaus.plexus:plexus-utils:jar:3.0.20:compile - omitted for duplicate)
    |  +- org.eclipse.aether:aether-impl:jar:1.0.0.v20140518:compile
    |  |  +- (org.eclipse.aether:aether-api:jar:1.0.0.v20140518:compile - omitted for duplicate)
    |  |  +- (org.eclipse.aether:aether-spi:jar:1.0.0.v20140518:compile - omitted for duplicate)
    |  |  \- (org.eclipse.aether:aether-util:jar:1.0.0.v20140518:compile - omitted for duplicate)
    |  +- org.eclipse.aether:aether-api:jar:1.0.0.v20140518:compile
    |  +- org.eclipse.aether:aether-util:jar:1.0.0.v20140518:compile
    |  |  \- (org.eclipse.aether:aether-api:jar:1.0.0.v20140518:compile - omitted for duplicate)
    |  +- org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.0.M1:compile
    |  |  +- javax.enterprise:cdi-api:jar:1.0:compile
    |  |  |  +- javax.annotation:jsr250-api:jar:1.0:compile
    |  |  |  \- (javax.inject:javax.inject:jar:1:compile - omitted for duplicate)
    |  |  +- org.eclipse.sisu:org.eclipse.sisu.inject:jar:0.3.0.M1:compile
    |  |  +- (org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile - omitted for duplicate)
    |  |  +- (org.codehaus.plexus:plexus-classworlds:jar:2.5.1:compile - omitted for conflict with 2.5.2)
    |  |  \- (org.codehaus.plexus:plexus-utils:jar:2.1:compile - omitted for conflict with 3.0.20)
    |  +- org.sonatype.sisu:sisu-guice:jar:no_aop:3.2.3:compile
    |  |  +- javax.inject:javax.inject:jar:1:compile
    |  |  +- aopalliance:aopalliance:jar:1.0:compile
    |  |  \- com.google.guava:guava:jar:16.0.1:compile
    |  +- org.codehaus.plexus:plexus-interpolation:jar:1.21:compile
    |  +- org.codehaus.plexus:plexus-utils:jar:3.0.20:compile
    |  +- org.codehaus.plexus:plexus-classworlds:jar:2.5.2:compile
    |  +- org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
    |  \- org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
    |     +- (org.codehaus.plexus:plexus-utils:jar:1.5.5:compile - omitted for conflict with 3.0.20)
    |     \- org.sonatype.plexus:plexus-cipher:jar:1.4:compile
    +- org.apache.maven:maven-plugin-api:jar:3.2.5:compile
    |  +- (org.apache.maven:maven-model:jar:3.2.5:compile - omitted for duplicate)
    |  +- (org.apache.maven:maven-artifact:jar:3.2.5:compile - omitted for duplicate)
    |  \- (org.eclipse.sisu:org.eclipse.sisu.plexus:jar:0.3.0.M1:compile - omitted for duplicate)
    +- org.apache.maven.plugin-tools:maven-plugin-annotations:jar:3.4:provided
    |  \- (org.apache.maven:maven-artifact:jar:3.0:provided - omitted for conflict with 3.2.5)
    +- org.apache.ant:ant:jar:1.9.3:compile
    |  \- org.apache.ant:ant-launcher:jar:1.9.3:compile
    +- org.bouncycastle:bcpg-jdk15on:jar:1.51:compile
    |  \- org.bouncycastle:bcprov-jdk15on:jar:1.51:compile
    +- junit:junit:jar:3.8.2:test
    \- org.mockito:mockito-core:jar:1.9.5:test
      +- org.hamcrest:hamcrest-core:jar:1.1:test
      \- org.objenesis:objenesis:jar:1.0:test

**Comment by infothrill** [comment]
Sorry for the confusion with the duplication. The pull request #206 now switches the method over to commons-lang instead of plexus utils.
