### ISSUE TITLE
Depends field should be left empty if a package depends on no other

### ISSUE THREAD

**Issue by rspieldenner** [tcurdt/jdeb#208]
the upgrade of Jdeb to 1.4 adds a default dependency of "default-jre | java6-runtime"

Not all packages need to depend on other packages. Also the debian control file syntax allows the Depends field to be omitted.

**Comment by tmortagne** [comment]
It's not really that simple. The idea behind this automatic depends is that jdeb has been designed for java projects (and is mostly used for java projects). You don't have any dependency on java in a Maven project for example but you still need Java to work if you are building a package for a jar.

Currently (since #190) when you don't want any dependency you can explicitly set an empty Depends.

**Comment by tcurdt** [comment]
I am also leaning towards not having a default anymore and adding it to all examples explicitly.

...but I have two concerns:

"default-jre | java6-runtime" is no longer a good default (given that we are at java8 now). Which begs the question what the default runtime should be? Just use java8? Changing it to java8 could almost as bad as just switching it to <empty>. The question is whether such a thing would be semantically OK for a 1.5 release.

Calling a release 2.0 just for that does not feel warranted - and this would change in 2.x anyway.

https://github.com/tcurdt/jdeb/issues/195

**Comment by tcurdt** [comment]
Since there is a work around to set it explicitly to empty I will close this issue for - but be sure it's kept in mind for 2.x. Thanks for reporting.

**Comment by ebourg** [comment]
The default version for the java<n>-runtime dependency could probably be derived from the target level used by the compiler plugin. But java6-runtime isn't that bad since this dependency is also satisfied by the Java 8 packages.

**Comment by tcurdt** [comment]
...and for ant?

Ah! Didn't know that java6-runtime is satisfied by java8 as well. That does make things a little easier if we want to change the default.

**Comment by ebourg** [comment]
For Ant we could default to the version of the JDK used to run jdeb.

**Comment by tcurdt** [comment]
Meh. I'd say just leave it for the 1.x branch.
And for the 2.x version it should be more obvious.

**Comment by rspieldenner** [comment]
This isn't absolutely true. Certain dependencies like asm are highly
sensitive to JRE version (3.x won't work in JRE 8, and 5.x doesn't work in
JRE 6).

**Comment by krushik** [comment]
The default list of possible dependencies (if reintroduced) should probably include 'java-runtime-headless', and/or 'default-jre' may be changed to 'default-jre-headless' as the thinnest requirement:

    $ apt-cache show openjdk-7-jre-headless | grep Provides
    Provides: java-runtime-headless, java2-runtime-headless, java5-runtime-headless, java6-runtime-headless, java7-runtime-headless
    $ apt-cache show default-jre | grep Depends
    Depends: default-jre-headless, openjdk-7-jre
    $ apt-cache show default-jre-headless | grep Depends
    Depends: openjdk-7-jre-headless (>= 7~u3-2.1.1)

**Comment by ebourg** [comment]
For now `java-runtime-headless` stands for Java 1, not really a good choice :) Also on some architectures `default-jre` doesn't pull OpenJDK but GCJ which is roughly equivalent to Java 5.

**Comment by tcurdt** [comment]
I think we screwed ourselves into a corner here. I would really love to rid of the default `Depends`. Maybe we should bite the bullet and just print out a warning if there is no `Depends`. Adding the one line to the control file isn't that big a deal.

Thoughts? @ebourg ?

**Comment by tcurdt** [comment]
Maybe let's get it into the 1.5 release and be done with it.
