### ISSUE TITLE
Publish artifact with dependency-reduced POM

### ISSUE THREAD

**Issue by tbroyer** [tcurdt/jdeb#214]
The POM uses the maven-shade-plugin to "shade" commons-io, commons-compress and bouncycastle into the produced JAR [1], but for some reason the deployed POM still references them [2].

[1] https://github.com/tcurdt/jdeb/blob/jdeb-1.4/pom.xml#L145-L152
[2] https://search.maven.org/#artifactdetails%7Corg.vafer%7Cjdeb%7C1.4%7Cmaven-plugin

**Comment by tmortagne** [comment]
Indeed included jars should probably be declared as \<scope>provided\</scope> to not be transitive.

**Comment by tcurdt** [comment]
Bummer - that fails the integration tests. Reverting for now.

**Comment by tcurdt** [comment]
Scope `provided` isn't actually needed. I think this was because of the relocation pattern - either way. I checked the current pom and it's fine.
