### ISSUE TITLE
Conffiles list created without paths rooted at '/'

### ISSUE THREAD

**Issue by sewe** [tcurdt/jdeb#221]
The following configuration (jdeb Maven plugin, version 1.4)

    <data>
      <type>file</type>
      <conffile>true</conffile>
      <src>${basedir}/src/deb/fs/etc/logrotate.d/example</src>
      <mapper>
        <type>perm</type>
        <prefix>/etc/logrotate.d</prefix>
      </mapper>
    </data>

produces a `conffiles` list of

    etc/logrotate.d/example

instead of

    /etc/logrotate.d/example

AFAIK, Debian requires a leading slash, though.

**Comment by tcurdt** [comment]
closing in favour of https://github.com/tcurdt/jdeb/issues/217
