### ISSUE TITLE
Handle insufficient temp space better

### ISSUE THREAD

**Issue by alert-debug** [tcurdt/jdeb#234]
If trying to create a .deb package on a system which has insufficient temp space, the stacktrace produced contains messages like:

org.vafer.jdeb.PackagingException: Could not create deb package
java.io.IOException: This archives contains unclosed entries.

but nothing which highlights the underlying issue.  This leads to confusion which presumably explains tickets like [this](https://github.com/tcurdt/jdeb/issues/192).

Having a separate check in [createSignedDeb](https://github.com/tcurdt/jdeb/blob/master/src/main/java/org/vafer/jdeb/DebMaker.java#L473) to catch the IOException and suggest a disk space problem (the most likely cause?) to the user would potentially speed up debugging this issue when people encounter it.

**Comment by tcurdt** [comment]
Fair point.

**Comment by tcurdt** [comment]
I guess this can now be closed as fixed then.
