### ISSUE TITLE
Getting packaging exception

### ISSUE THREAD

**Issue by shanujbansal** [tcurdt/jdeb#236]
Hi,
I am trying to create a debian package from my source. I have checked the src parameters which are correct. When I run my ant task to create the deb package, I get this error.
 
[deb] org.vafer.jdeb.PackagingException: Could not create deb package
      [deb] 	at org.vafer.jdeb.Processor.createDeb(Processor.java:171)
      [deb] 	at org.vafer.jdeb.ant.DebAntTask.execute(DebAntTask.java:230)
      [deb] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:291)
      [deb] 	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
      [deb] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
      [deb] 	at java.lang.reflect.Method.invoke(Method.java:606)
      [deb] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
      [deb] 	at org.apache.tools.ant.Task.perform(Task.java:348)
      [deb] 	at org.apache.tools.ant.Target.execute(Target.java:390)
      [deb] 	at org.apache.tools.ant.Target.performTasks(Target.java:411)
      [deb] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1399)
      [deb] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1368)
      [deb] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
      [deb] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
      [deb] 	at org.apache.tools.ant.Main.runBuild(Main.java:809)
      [deb] 	at org.apache.tools.ant.Main.startAnt(Main.java:217)
      [deb] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
      [deb] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)
      [deb] Caused by: java.lang.NullPointerException
      [deb] 	at org.vafer.jdeb.utils.Utils.replaceVariables(Utils.java:120)
      [deb] 	at org.vafer.jdeb.descriptors.AbstractDescriptor.set(AbstractDescriptor.java:118)
      [deb] 	at org.vafer.jdeb.descriptors.AbstractDescriptor.parse(AbstractDescriptor.java:93)
      [deb] 	at org.vafer.jdeb.descriptors.PackageDescriptor.<init>(PackageDescriptor.java:75)
      [deb] 	at org.vafer.jdeb.Processor.createPackageDescriptor(Processor.java:373)
      [deb] 	at org.vafer.jdeb.Processor.buildControl(Processor.java:311)
      [deb] 	at org.vafer.jdeb.Processor.createDeb(Processor.java:139)
      [deb] 	... 17 more

Could you please help me resolve this. Been stuck over here for almost more than a day now.
P.S. I am using jdeb1.0.1

**Comment by tcurdt** [comment]
From the stack trace I do see that there is an exception during variable expansion.
Please upgrade to jdeb-1.5. It's hard to give support for such a (very) old version.

**Comment by shanujbansal** [comment]
Thanks Torsten. Switching to jdeb-1.5 worked wonders for me. Now I am able to create the debian package. Thanks a lot for the help.
