### ISSUE TITLE
use UTC for timestamp in convertToDebianVersion

### ISSUE THREAD

**Issue by dbyron0** [tcurdt/jdeb#238]
As requested in https://github.com/tcurdt/jdeb/issues/195#issuecomment-220544059, here's a separate request to change the the timestamp in **convertToDebianVersion** to UTC.  You're right that there are consequences for people using timestamps from some other timezone when they switch to UTC, at least when that other timezone has a positive offset from UTC.

Consider two snapshots made one right after the other -- the first with the existing code, and the second with UTC.

For negative offsets (i.e. west of Greenwich), or no offset at all, dpkg --compare-versions works as expected: the second snapshot is considered newer than the first.

For positive offsets (i.e. east of Greenwich), the dpkg --compare-versions considers the second snapshot older than the first, so manual removal, or --force, etc. is required to get the second snapshot to install.

Another way of thinking about this:  if the first UTC snapshot is at least as long after the last pre-UTC snapshot as the UTC offset (e.g. >= 2 hours between snapshots in UTC+2), there's no problem.

**Comment by Pham1993** [comment]
brew install helm

**Comment by Pham1993** [comment]
### 

> ``
