### ISSUE TITLE
Maintainer in mvn example is not according to the standard

### ISSUE THREAD

**Issue by bogdartysh** [tcurdt/jdeb#243]
Hi, when working with examples (Ubuntu 14) I've found that maintainer is not fully in accordance to the standard:

> E: jdeb-example: maintainer-name-missing tcurdt@vafer.org

I think it should be something like 

> name surname email@example.com

**Comment by ebourg** [comment]
The expected syntax is:

    John Doe <john.doe@example.com>

**Comment by bogdartysh** [comment]
something like: https://github.com/tcurdt/jdeb/pull/244

**Comment by ebourg** [comment]
or:

    Maintainer: Torsten Curdt <tcurdt@vafer.org>
