### ISSUE TITLE
[ant] tarfileset fullpath is ignored

### ISSUE THREAD

**Issue by rednoah** [tcurdt/jdeb#245]
The [tarfileset](https://ant.apache.org/manual/Types/tarfileset.html) attribute `fullpath` seems to be ignored:
```xml
<tarfileset fullpath="/usr/share/jdeb/bin/jdeb" file="${dist}/jdeb_1.2-r3.sh" />
```

`verbose` log:
```
file:./jdeb_1.2-r3.sh
```

The expected behaviour would be that `fullpath` defines the file path in the tar archive.

**Comment by rednoah** [comment]
🍺🍻💰💸🏴‍☠️

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=38938847)](https://www.bountysource.com/issues/38938847-ant-tarfileset-fullpath-is-ignored?utm_source=38938847&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by dirb** [comment]
@rednoah I made a PR to fixed it, could you verify it?

**Comment by rednoah** [comment]
Code looks good. Unfortunately, I don't have an easy way to test this right now.

Adding a test case to `testbuild.xml` would probably be a good idea though:
https://github.com/tcurdt/jdeb/blob/master/src/test/resources/testbuild.xml

**Comment by rednoah** [comment]
e.g.
```xml
  <target name="tarfileset-fullpath">
    <deb destfile="test.deb" control="org/vafer/jdeb/deb/control">
        <tarfileset fullpath="/usr/local/bin/test" file="org/vafer/jdeb/deb/data/test.sh" />
    </deb>
  </target>
```
The log should then say:
```
file:/usr/local/bin/test
```

**Comment by dirb** [comment]
It works for me, but I had to add `verbose="true"` to get the that output line
```xml
<deb destfile="test.deb" control="org/vafer/jdeb/deb/control" verbose="true">
```
and I get `file:./usr/local/bin/test` not `file:/usr/local/bin/test`, but I think it's because _tar_ tends to remove leading `/` from member names

**Comment by rednoah** [comment]
That's fine.

In the original test:
```
<tarfileset fullpath="/usr/share/jdeb/bin/jdeb" file="${dist}/jdeb_1.2-r3.sh" />
```
would yield:
```
file:./jdeb_1.2-r3.sh
```
The bug didn't allow me to override the path/filename with `fullpath`. `/usr/share/jdeb/bin/jdeb` or `./usr/share/jdeb/bin/jdeb` would be equally fine.

Feel free to claim the Bounty.

**Comment by tcurdt** [comment]
@rednoah big thanks for providing the bounty to support the project and it's contributors.
