### ISSUE TITLE
changes file overrides deb file if extension is not .deb

### ISSUE THREAD

**Issue by rednoah** [tcurdt/jdeb#246]
If `destfile` in the `jdeb` ant task does not end with `.deb` then it doesn't correctly derive the `.changes` file and ends up overriding the deb package we just created:

Log:
```
Creating changes file: ~/MyApp/dist/MyApp_1.0_noarch.ipk
```

Since `.deb` and `.ipk` files are the same thing, I'd be nice if creating `.deb` packages with `.ipk` extension was possible.

**Comment by rednoah** [comment]
This line assumes that the output path ends with `.deb`, and if that's not the case then the changes file will have the same path as the package file:
https://github.com/tcurdt/jdeb/blob/f466c098c9acfb0dabc2d69f3ef914a2bbe9baae/src/main/java/org/vafer/jdeb/DebMaker.java#L355

I'd be an easy fix for the `1.6` milestone. ;)

**Comment by tcurdt** [comment]
@rednoah indeed - that's a broken window :)

I am happy to accept a PR if you want to get this fixed.
