### ISSUE TITLE
debsigs as signMethod

### ISSUE THREAD

**Issue by danielburrell** [tcurdt/jdeb#249]
Am trying to sign a package such that only the .deb file is required (the signature should be contained inside the .deb file).
Currently with the methods provided the signature is contained within a separate 'changes' file and the .deb artifact itself is not signed.

I'm not an expert in deb tooling, but I saw this blog: https://blog.packagecloud.io/eng/2014/10/28/howto-gpg-sign-verify-deb-packages-apt-repositories/
specifically this line which seems to allow signing of the packages themselves as selfcontained packages:

`$ debsigs --sign=origin -k E732A79A test_1.0-7_amd64.deb`

Have I misunderstood? or is there a way to do that with the tools provided already in signMethod (dpkg-sig, debsig-verify).

If not, is this a feature you'd consider?

**Comment by tcurdt** [comment]
@danielburrell to be completely honest - it's been a looong time since I used the signing.

Could you provide a test project or at least some output/files to look at?

**Comment by danielburrell** [comment]
Sorry about the delay, I have this project here, not a 'test' project in that it has code but it does contain the example jdeb setup that attempts a signing.

https://github.com/danielburrell/schema.tf

Key thing is that the signing tooling provided by jdeb doesn't seem to cover the debsigs tool (debsigs allows you to sign a package by embedding the gpg signature inside).

Debsigs seems to have the idea of generating a signature but then embedding that signature file inside the debian package.

Implementation of debsigs seems to be here in the cmd_sign method:
https://gitlab.com/debsigs/debsigs/blob/master/debsigs
It 'just calls' gpg to grab a signature of the package, and then opens the package and stuffs the signature inside. I say "just" of course it's all in perl... and it seems to pick and choose the contents that it's signing.

Not sure on the internals of jdeb so again, unsure if this feature already exists and I missed it, or if it's too tricky to implement.

**Comment by tcurdt** [comment]
@danielburrell looking at [the code](https://github.com/tcurdt/jdeb/blob/master/src/main/java/org/vafer/jdeb/DebMaker.java#L546) this should already be supported.

**Comment by danielburrell** [comment]
ah, ok on closer inspection it does actually work out of the box. 7zip (tool I was using to check the deb file) wouldn't show the _gpg signature file for some reason. But debsig-verify did successfully validate the package so it must be there!

Awesome Thanks!

**Comment by tcurdt** [comment]
@danielburrell glad it worked out :)

If you think documentation should better cover this a PR would be much welcome!
