### ISSUE TITLE
Maven warns that jdeb is not marked as thread-safe

### ISSUE THREAD

**Issue by dheid** [tcurdt/jdeb#256]
If I use the jdeb plugin and execute with multiple threads, e.g. `mvn package -T8`, Maven reports the following warning:

```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that are not marked as       *
[WARNING] * @threadSafe to support parallel building.                     *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe:
[WARNING] org.vafer:jdeb:1.5
[WARNING] *****************************************************************
```

Is jdeb thread safe?

**Comment by tcurdt** [comment]
@dheid do you know what exactly is running in parallel here? Everything that comes after the artifact generation?

**Comment by dheid** [comment]
According to https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3 each module will be built in an own thread in relation to the sub-module dependency structure.Modules could be executed in parallel. Therefore it is necessary, that an instance could be executed multiple times without threading issues. This could happen in case of shared static variables.Am 06.04.2017 16:45 schrieb Torsten Curdt <notifications@github.com>:@dheid do you know what exactly is running in parallel here? Everything that comes after the artifact generation?

**Comment by tcurdt** [comment]
Looks like all the statics we have are immutable - so I guess we should be fine.

**Comment by tcurdt** [comment]
Thanks guys!
