### ISSUE TITLE
How to create debian package for multi-module project?

### ISSUE THREAD

**Issue by UmeshRajani** [tcurdt/jdeb#260]
Suppose I have 20 sub-project under the parent project, in that case how can we make possible to make debian

Thank you,
Umesh

**Comment by ebourg** [comment]
This really depends on your project. If each module needs a separate package, just configure the jdeb plugin in each pom.xml. If most modules are intermediate libraries that don't need to be packaged separately, create a module dedicated to building the Debian package that will group all the required libraries into the same package. You can get a look at the [Jsign](https://github.com/ebourg/jsign) project for an example.

**Comment by tcurdt** [comment]
@UmeshRajani I assume this answers your question? Hence closing.
