### ISSUE TITLE
Dynamic variable version is replace by ~ instead of -SNAPSHOT why ?

### ISSUE THREAD

**Issue by rodorico** [tcurdt/jdeb#261]
Having plugin version 1.5 when I generate the deb package from a SNAPSHOT version. and used dynamic variable like project version in the control files Version: [[version]] is replaced by ~SNAPSHOT instead of "-SNAPSHOT". 
Why this behavior ??

**Comment by ebourg** [comment]
Because snapshot versions are before non snapshot versions, and the way Debian compares package versions you have this kind of order:

    1.0~SNAPSHOT < 1.0 < 1.0-SNAPSHOT

**Comment by tcurdt** [comment]
@rodorico I guess the question was answered? Hence the closing.

**Comment by rodorico** [comment]
yes please it.
