### ISSUE TITLE
Regression in creating directory with DataProducer together with PermMapper between version 1.4 and 1.6

### ISSUE THREAD

**Issue by chali** [tcurdt/jdeb#264]
We are creating directories using `DataProducerPathTemplate` and setting permission using `PermMapper` When I'm reading the content of produced deb I see different results between jdeb 1.4 and 1.6. I register directory `/var/logs/directory' with 1.4 I'm reading `/var/logs/directory` with 1.6 I'm getting `//var/logs/directory`

I believe it is related to change in version of commons-compress from 1.8 to 1.15 and its different implementation of `setName` used in [`PermMapper`](https://github.com/tcurdt/jdeb/blob/fb8d15bf0b0c5daed7a80f760a24ebd9d741832a/src/main/java/org/vafer/jdeb/mapping/PermMapper.java#L60)

[`setName` in commons-compress:1.8](https://github.com/apache/commons-compress/blob/rel/1.8/src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveEntry.java#L390)
[`setName` in commons-compress:1.15](https://github.com/apache/commons-compress/blob/rel/1.15/src/main/java/org/apache/commons/compress/archivers/tar/TarArchiveEntry.java#L440)

Here is an [complete example](https://github.com/chali/directoryNameRegression) which shows the difference

**Comment by tcurdt** [comment]
I remember a discussion that paths actually should be relative all the time with no leading slashes at all. I guess this needs to be checked and the code adjusted accordingly.

**Comment by tcurdt** [comment]
Thanks for digging into this. Seems like it really was just a bug in the `PermMapper`.
The right thing to do would be write a test case for the `PermMapper`, but I think it shoulds be fixed now. Let me know.
