### ISSUE TITLE
Jdeb making unwarranted changed to control files (install scripts)

### ISSUE THREAD

**Issue by leeMarchello** [tcurdt/jdeb#271]
When using Jdeb to build the debian package I've noticed that it switches the order of brackets inside the install scripts (i.e postinst, preinst, prerm etc).

Inside my postinst file I have code that looks like the following:

`line = line.replace('@ALLOW_BATCH_FILTER@', config[self.client]['ALLOW_BATCH_FILTER'])`
After the deb is built this particular line inside the postinst is altered to look like this:

` line = line.replace('@ALLOW_BATCH_FILTER@', config[self.client[]'ALLOW_BATCH_FILTER'])
`
So in essence when the plugin encounters "] ["  it will switch them around to look like this "[ ]". This should not be happening because it prevents my deb package from installing as it complains that there is syntax error in the code. The install scripts are written in python.

This is likely a bug unless theres a configuration change to prevent this from happening.

**Comment by tcurdt** [comment]
It would be great if you could provide a testcase for this by adding it here:

https://github.com/tcurdt/jdeb/blob/master/src/test/java/org/vafer/jdeb/utils/FilteredFileTestCase.java

**Comment by tcurdt** [comment]
and/or here

https://github.com/tcurdt/jdeb/blob/master/src/test/java/org/vafer/jdeb/utils/UtilsTestCase.java

**Comment by leeMarchello** [comment]
Excuse my ignorance, but this is my first time ever posting a issue on github so I am not entirely sure what I need to do. Should I add a test case into the same directory and upload it to github ? Please could you provide me with more details on what I need to do here.

**Comment by leeMarchello** [comment]
Thank you for the guidance, so I've gone ahead and forked jdeb, added the sample test case directly into the FilteredFileTestCase class and then submitted a pull request. Hopefully I've done the right way as you expected it to be. If not please let me know. Thanks

**Comment by tcurdt** [comment]
```
org.junit.ComparisonFailure: unexpected resolve for #!/usr/bin/python3 -B
line = line.replace('@ALLOW_BATCH_FILTER@', config[self.client]['ALLOW_BATCH_FILTER']) expected:<..., config[self.client[]['ALLOW_BATCH_FILTER'])]> but was:<..., config[self.client[[]'ALLOW_BATCH_FILTER'])
]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.vafer.jdeb.utils.FilteredFileTestCase.testTokenSubstitutionWithinOpenCloseTokens(FilteredFileTestCase.java:71)
```
Seems like the state machine of the variable resolver has a bug. Should be a low hanging fruit to fix here:

https://github.com/tcurdt/jdeb/blob/master/src/main/java/org/vafer/jdeb/utils/Utils.java#L107
