### ISSUE TITLE
How to set package license

### ISSUE THREAD

**Issue by Sami32** [tcurdt/jdeb#276]
Argh i didn't saw any way to set a license. Unbuntu 18.04 throw that it is proprietary license because none has been added.
`License:` or `<license>GPLv2</license>`

Is there is a way to set the package license? I really hope that i have missed it.

**Comment by Sami32** [comment]
I was not able to see this mandotory field in the code.
https://www.debian.org/doc/manuals/maint-guide/dreq.fr.html#copyright
`<copyrightDir>` ?

**Comment by tcurdt** [comment]
There is no such field in the [control file](https://www.debian.org/doc/debian-policy/ch-controlfields.html) but I think you are talking about [`debian/copyright` file ](https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/)

Also see https://www.debian.org/doc/manuals/maint-guide/dreq.en.html

**Comment by tmortagne** [comment]
> There is no such field in the control file

Made me realize I made the exact same mistake. The funny thing is that in Ubuntu I cannot find a single package in /var/cache/apt/archive which provide the license (was searching for examples).

**Comment by Sami32** [comment]
Thank for you answer +1
I've only realized that later. I was also searching for example ;)

It should be a nice enhancement to add this feature in jdeb 2.0 ;)

**Comment by tcurdt** [comment]
> It should be a nice enhancement to add this feature in jdeb 2.0 ;)

How would you imagine that feature to be working?

**Comment by Sami32** [comment]
I was thinking of adding it in your Maven example, like:
```
<data>
	<src>${project.build.directory}/changelog.gz</src>
	<dst>/usr/share/doc/${project.name.camel}/changelog.gz</dst>
	<type>file</type>
</data>
<data>
	<src>${project.external-resources}/linux/debian/copyright</src>
	<dst>/usr/share/doc/${project.name.camel}/copyright</dst>
	<type>file</type>
</data>
```
And add 2 generic template files into your code, like:
```
Format: http://www.debian.org/doc/packaging-manuals/copyright-format/1.0/
Upstream-Name: Digital Media Server
Upstream-Contact: Nadahar <nadahar@digitalmediaserver.org>
Source: https://github.com/DigitalMediaServer/DigitalMediaServer/releases

Files: *
Copyright: Copyleft (©) 2016-2018 Digital Media Server.
Licence: GPL-3.0

  This program is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 3 of the License, or any
  later version.

  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License with
  the Debian GNU/Linux distribution in file /usr/share/common-licenses/GPL;
  if not, write to the Free Software Foundation, Inc., 59 Temple Place,
  Suite 330, Boston, MA  02111-1307  USA

                    GNU GENERAL PUBLIC LICENSE
                       Version 3, 29 June 2007
...
```


I'm sure that it came like an evidence to you but when we are not from Linux world it doesn't ;)

**Comment by tmortagne** [comment]
Since the Maven pom contains a <licenses> information (if you provide it) it would make sense to generate a copyright files which contains it by default (associated to `File: *`).

**Comment by Sami32** [comment]
Adding the copyright file didn't make it, as PackageKit show:
```
Package description
  package:     dms-0.3.0-SNAPSHOT.all
  summary:     Media server
  license:     unknown
  group:       programming
  description: Media server
  size:        55926352 bytes
  url:         http://www.digitalmediaserver.com/
```

**Comment by Sami32** [comment]
Do you have any reference package in mind?

**Comment by tcurdt** [comment]
@Sami32 Just like @tmortagne I would have expected the latest Ubuntu packages to have this. Maybe check an official Debian packages.

**Comment by Sami32** [comment]
Sorry i've no idea as i've never used it not knowing it.

**Comment by Sami32** [comment]
@tcurdt Thank you for making me discover that tool :+1:
lintian is great, perhaps a little too much when i see all these errors and warning;)

It seem that the changelog and copyright files are not set in the correct place inside the package
>E: dms: changelog-file-missing-in-native-package
E: dms: no-copyright-file
E: dms: extended-description-is-empty

But there are in as they are been found in the /usr/share/docs folders after install.
So yest it seem that the plugin doesn't work as expected, but it will not doesn't change that Ubuntu Software manager have its own issue.

**Comment by Sami32** [comment]
@tcurdt That said when i read that:
>E: dms: systemd-service-file-outside-lib usr/lib/systemd/system/dms.service

I'm wondering if lintian is reliable?
Because i thought i've followed Debian specifications.

**Comment by Sami32** [comment]
Ah ok, i get these Lintian errors because the project name and folder was not the same.

**Comment by tmortagne** [comment]
> Since the Maven pom contains a <licenses> information (if you provide it) it would make sense to generate a copyright files which contains it by default (associated to File: *).

That's actually #106 I think :)

**Comment by Sami32** [comment]
Hehe, yes ;)
I just forgot the extra dot that i had set in the name, i become senile i guess ;)
