### ISSUE TITLE
Incorrect symlink example:  "symlink-should-be-relative"

### ISSUE THREAD

**Issue by Sami32** [tcurdt/jdeb#278]
Lintian will report that as incorrect and ask to follow the Debian policy that say that in such case the symlink should be relative.
https://github.com/tcurdt/jdeb/blob/93a2699b836a3d44fc14e8eb08611eefd7024ea3/src/examples/maven/pom.xml
```
<data>
                        <type>link</type>
                        <symlink>true</symlink>
                        <linkName>/usr/share/java/jdeb.jar</linkName>
                        <linkTarget>/usr/share/jdeb/lib/${project.build.finalName}.jar</linkTarget>
</data
```

**Comment by tcurdt** [comment]
Do you have a link to that policy?

**Comment by Sami32** [comment]
https://lintian.debian.org/tags/symlink-should-be-relative.html
