### ISSUE TITLE
Mvn deploy

### ISSUE THREAD

**Issue by JuanJoseRodriguezMenendez** [tcurdt/jdeb#285]
Hi I was trying to deploy the deb that i'm generating into a nexus apt repository, the pom.xml looks similar to the example in "Or if you want to build a custom deb file" section in the documentation for maven, but i'm getting this error 

Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy (default-deploy) on project <projectName>: ArtifactDeployerException: Failed to deploy artifacts: Could not transfer artifact <groupId>:<artifactId>:deb:0.2 from/to nexus (http://localhost:8081/repository/AptLocal/): Failed to transfer file: http://localhost:8081/repository/AptLocal/<groupId>/<artifactId>/<version>/<artifactId>-<version>.deb. Return code is: 405, ReasonPhrase: PUT

Do you have any example of the necessary config to make this work, or any idea of what could be wrong?

**Comment by tcurdt** [comment]
I personally never used `jdeb` with nexus. In fact I didn't even know it provides an apt repository.
I'll keep this open despite not really being a jdeb problem. Maybe someone else know.
Let us know if you can figure it out.

**Comment by JuanJoseRodriguezMenendez** [comment]
I had to make a "dirty" solution, using the exec-maven-plugin for making a curl to the repository

If anyone know a better way to do this please let us know

**Comment by tcurdt** [comment]
closing this for now
