### ISSUE TITLE
Jdeb should have a sysprop for skipping execution

### ISSUE THREAD

**Issue by exabrial** [tcurdt/jdeb#286]
Hey thanks for a great plugin!

Most every other maven plugin has a default system property that can skip it's execution (example: `-Dmaven.test.skip`). While you do have a config option to skip, it would be great if there was a default system property.

cheers,
-Jonathan

**Comment by tcurdt** [comment]
Could you outline how that would be different to the `skip` option?

**Comment by exabrial** [comment]
Sure. Nearly every Maven plugin does this. Take a look at: https://gleclaire.github.io/findbugs-maven-plugin/check-mojo.html#skip

They have a configuration item for `skip`, but they also allow a default system property called `findbugs.skip` that can be specified at the command line: `mvn clean install -Dfindbugs.skip=true`

So while jdeb allows a skip in the pom.xml, it does not allow it to be overriden at build time with a default system property. Something like `mvn clean install -Djdeb.skip=true`

Other notable examples:
* https://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#skip `mvn clean install -Dmaven.test.skip=true`
* https://maven.apache.org/plugins/maven-pmd-plugin/check-mojo.html#skip `mvn clean install -Dpmd.skip=true`

**Comment by tcurdt** [comment]
That sounds pretty easy to add. Happy to accept a patch.
