### ISSUE TITLE
Does not append file

### ISSUE THREAD

**Issue by benchdoos** [tcurdt/jdeb#287]
Hello!
Can someone explane how appending of files to deb package?
I have builded, packaged jar: `target/application.jar`
In maven I've addded plugin:
```
<plugin>
    <groupId>org.vafer</groupId>
    <artifactId>jdeb</artifactId>
    <version>1.7</version>
    <executions>
        <execution>
            <phase>package</phase>
            <goals>
                <goal>jdeb</goal>
            </goals>
            <configuration>
                <dataSet>
                    <data>
                        <!--project.name equals to jar name-->
                        <src>${project.build.directory}/${project.name}.jar</src>
                        <type>file</type>
                    </data>
                </dataSet>
            </configuration>
        </execution>
    </executions>
</plugin>
```
Calling is: `mvn jdeb:jdeb`

Package deb contains `data.tar.gz`, that is empty.
What's beeng wrong?
Thank you.

**Comment by tcurdt** [comment]
You mean you want to add more files to the deb than just the jar? Did you have a look at the [example yet](https://github.com/tcurdt/jdeb/blob/master/src/examples/maven/pom.xml)?

And `jdeb` is being called automatically during the build. There is no need for calling it as `jdeb:jdeb`

**Comment by benchdoos** [comment]
> Did you have a look at the example yet?

Yes, I did 

> You mean you want to add more files to the deb than just the jar? 

Just a jar.

Ok, the issue is - jdeb works on package phase, but if jar is already packaged (without package phase (for example through maven-assembly-plugin)), it does not include anything.

Okay, I'll try to rebuild project without this plugin, I'll respond what I got.
