### ISSUE TITLE
changesfile "Changed-By" parameter overriden by "Maintainer"

### ISSUE THREAD

**Issue by mrasko** [tcurdt/jdeb#291]
Inside the ChangesFileBuilder:createChanges first `ChangesFile.setChanges` is called that sets the "Changed-By" to what's in the most recent changeset.

The issue is that right after that the `ChangesFile.initialize` is called which overrides it with "Maintainer" info from control file.

**Comment by tcurdt** [comment]
Thanks for reporting. Care to provide a PR?

**Comment by mrasko** [comment]
Sure, no problem.
