### ISSUE TITLE
Field length limit of 100 - possible to extend

### ISSUE THREAD

**Issue by rpalcolea** [tcurdt/jdeb#296]
hi @tcurdt,

This is related to https://github.com/tcurdt/jdeb/issues/241

After taking a look, it seems that this isn't only associated with gnu vs posix.

The exception that we get with long paths is the following:

`Caused by: java.lang.IllegalArgumentException: Field '/var/log/loooongnameloooongnameloooongnameloooongnameloooongnameloooongnameloooongnameloooongnameloooongnameloooongnameloooongnameloooongnameloooongnameloooongnameloooongnameloooongnameloooongnameloooongnameloooongnameloooongname' too long, maximum is 100
`

Switching to `maker.setTarLongFileMode('posix')` isn't enough because of this: https://github.com/tcurdt/jdeb/blob/master/src/main/java/org/vafer/jdeb/DataBuilder.java#L172

` checkField(entry.getLinkName(), TarConstants.NAMELEN);` 

`TarConstants.NAMELEN` is always 100 (https://commons.apache.org/proper/commons-compress/apidocs/constant-values.html#org.apache.commons.compress.archivers.tar.TarConstants.NAMELEN) regardless of the long file mode.  

Is this something you could fix to stop relying on the constant for `linkName` ?

**Comment by tcurdt** [comment]
Sounds like you are right.
I am little hesitant to just remove it completely without a test case covering both cases though.
But with I would be happy to accept a PR (otherwise it might take a bit until I come around to look into it).

**Comment by rpalcolea** [comment]
hi @tcurdt , thanks for the quick response.
Which two cases are you referring to? I'll be more than happy to introduce test cases for both

**Comment by tcurdt** [comment]
@rpalcolea since `buildData` supports the options `gnu` and `posix` 
https://github.com/tcurdt/jdeb/blob/master/src/main/java/org/vafer/jdeb/DataBuilder.java#L97
I would suggest to unit test the overflow behaviour of both of these cases.

**Comment by rpalcolea** [comment]
Let me know if this is enough https://github.com/tcurdt/jdeb/pull/297
