### ISSUE TITLE
Maven link is broken

### ISSUE THREAD

**Issue by thhart** [tcurdt/jdeb#342]
In your README.md you have a wrong Maven package link.

**Comment by tcurdt** [comment]
Could you be more specific?

These all work for me:

http://github.com/tcurdt/jdeb/blob/master/docs/maven.md
http://repo1.maven.org/maven2/org/vafer/jdeb/

**Comment by thhart** [comment]
![Screenshot_2021-04-21_21-13-10](https://user-images.githubusercontent.com/2632538/115608365-73911d80-a2e6-11eb-9455-454d0fe18a5b.png)
This is what I get when I click: http://repo1.maven.org/maven2/org/vafer/jdeb/ (in Firefox and Chrome)
Maybe you have an automatic https redirect.

**Comment by tcurdt** [comment]
I am getting redirected to https://repo1.maven.org/maven2/org/vafer/jdeb/ with Chrome.
But I just changed it to directly link to https

**Comment by tcurdt** [comment]
Please close if this works for you now.
