### ISSUE TITLE
User creation

### ISSUE THREAD

**Issue by thhart** [tcurdt/jdeb#343]
When installing with a specific user name configured, is the creation of a unknown user supported?

**Comment by thhart** [comment]
I can see it is possible via postinst/preinst files. Am I correct?

**Comment by ebourg** [comment]
You can indeed do this with a postinst script, or declaratively with a sysusers file installed in `/usr/lib/sysusers.d/` . See for example the file used by the tomcat9 package in Debian:

https://salsa.debian.org/java-team/tomcat9/-/blob/master/debian/sysusers/tomcat9.conf

This requires a dependency on systemd (>= 238).
