### ISSUE TITLE
Little problem with IDEA Maven

### ISSUE THREAD

**Issue by thhart** [tcurdt/jdeb#344]
I am using Intellij Idea and its Maven integration, when I call the jdep or install target within IDEA the resulting deb is empty. When calling 'mvn install' from console everything goes well. I know it is probably related to IDEA but do you have a short idea what might be the issue?

The output in IDEA is like this:

<pre>
/home/th/.jdks/openjdk-15/bin/java -Dmaven.multiModuleProjectDirectory=/home/th/dev/os/collector -Dmaven.home=/opt/idea-IU-201.7223.91/plugins/maven/lib/maven3 -Dclassworlds.conf=/opt/idea-IU-201.7223.91/plugins/maven/lib/maven3/bin/m2.conf -Dmaven.ext.class.path=/opt/idea-IU-201.7223.91/plugins/maven/lib/maven-event-listener.jar -javaagent:/opt/idea-IU-201.7223.91/lib/idea_rt.jar=41799:/opt/idea-IU-201.7223.91/bin -Dfile.encoding=UTF-8 -classpath /opt/idea-IU-201.7223.91/plugins/maven/lib/maven3/boot/plexus-classworlds-2.6.0.jar:/opt/idea-IU-201.7223.91/plugins/maven/lib/maven3/boot/plexus-classworlds.license org.codehaus.classworlds.Launcher -Didea.version=2021.1 org.vafer:jdeb:1.8:jdeb
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------------< com.itth:collector >-------------------------
[INFO] Building collector 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- jdeb:1.8:jdeb (default-cli) @ collector ---
[INFO] Creating debian package: /home/th/dev/os/collector/target/collector_1.0~SNAPSHOT_all.deb
[INFO] Building conffiles
[INFO] Skipping 'conffiles' generation. No entries defined in maven/pom or ant/build.xml.
[INFO] Creating changes file: /home/th/dev/os/collector/target/collector_1.0~SNAPSHOT_all.changes
[INFO] Attaching created debian package /home/th/dev/os/collector/target/collector_1.0~SNAPSHOT_all.deb
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.822 s
[INFO] Finished at: 2021-04-21T20:59:49+02:00
[INFO] ------------------------------------------------------------------------

Process finished with exit code 0
</pre>

**Comment by tcurdt** [comment]
I would suggest to run both (cli and idea) builds in verbose mode and then compare the output.
Unfortunately I am not sure how Intellij does the maven integration and how this could affect this.

**Comment by thhart** [comment]
I did call install:install instead of the lifecycle install target. When calling the second one it is working within IDEA.
Thanks for fast response and cool project.
