### ISSUE TITLE
conffile paths are not absolute anymore for mapped files

### ISSUE THREAD

**Issue by tmortagne** [tcurdt/jdeb#364]
Looks like a change in jdeb 1.9 caused paths inserted in the generated `conffiles` to not be absolute anymore.

For example, what used to be `/etc/xwiki/cache/infinispan/config.xml` became `etc/xwiki/cache/infinispan/config.xml` after upgrading to jdeb 1.9 with the pom:

```
            <data>
              <src>${war.path}/WEB-INF</src>
              <type>directory</type>
              <excludes>**/lib,**/lib/*,**/classes,**/classes/*,**/hibernate.cfg.xml,**/web.xml,**/xwiki.cfg,**/xwiki.properties</excludes>
              <mapper>
                <type>perm</type>
                <prefix>/etc/xwiki</prefix>
              </mapper>
              <conffile>true</conffile>
            </data>
```

I did not noticed at first because I could upgrade XWiki without any problem on Debian Stretch (dpkg 1.18.25) but Ubuntu 21.04 (dpkg 1.20.9ubuntu1) is really not a fan and simply refuse this conffile with the following errors:

```
 Preparing to unpack …/xwiki-tomcat9-common_13.5_all.deb …
 dpkg: error processing archive /var/cache/apt/archives/xwiki-tomcat9-common_13.5_all.deb (–unpack):
 conffile name ‘etc/systemd/system/tomcat9.service.d/xwiki-tomcat9-systemd.conf’ is not an absolute pathname
 Preparing to unpack …/xwiki-common_13.5_all.deb …
 dpkg: error processing archive /var/cache/apt/archives/xwiki-common_13.5_all.deb (–unpack):
 conffile name ‘etc/xwiki/cache/infinispan/config.xml’ is not an absolute pathname
 ```

**Comment by tmortagne** [comment]
Sounds like something to fix in `DebMaker#populateConffiles` but I guess the first thing to do is add a conffiles unit test :)

**Comment by tmortagne** [comment]
> They should be listed as absolute pathnames, and should exist in the binary package, otherwise dpkg(1) will ignore them

This seems to explains the difference between Debian Stretch and Ubuntu 21.04, looks like they decided to produce error instead of ignoring those in recent dpkg versions.

**Comment by tmortagne** [comment]
> Sounds like something to fix in DebMaker#populateConffiles

Actually, it seems to have more to do with how the mapper is interpreted.

**Comment by tmortagne** [comment]
So the cause is the following change: https://github.com/gesellix/jdeb/commit/124a6f564ad2520bc7d5750b0e0ec8720d43372a#diff-3ba26362bc4e5de49c9289bacaf1d572b90ab3c0cf99ea3fc2a41cc04d750146R59

It causes the removal of the leading "/" from the "/etc/xwiki" example.

**Comment by gesellix** [comment]
Leaving only a short response now that I got aware of your question. I need to have a deeper look into the actual .deb specs.

I can only tell that #336 reverted the behaviour to produce relative paths (also refering to  https://github.com/tcurdt/jdeb/issues/264#issuecomment-385158991), because of failing tests at the https://github.com/gesellix/gradle-debian-plugin.

Actually, we _might_ not only have to revert #336, but maybe keep it and add another step of converting the relative paths to absolute ones.

**Comment by gesellix** [comment]
Quoting https://github.com/gesellix/gradle-debian-plugin/pull/18#issue-609164556:

> Currently, it seems like JDeb 1.7 and 1.8 produce absolute instead of relative paths, which makes `lintian` fail.

So, is `lintian` wrong or did I fail to use it correctly?

**Comment by tmortagne** [comment]
> So, is lintian wrong or did I fail to use it correctly?

Depends on where it fails exactly. It feels like the same code is used for very different thing and the fact that it impacted conffiles (which must be absolute according to the specifications) is more of a unexpected side effect.

**Comment by tcurdt** [comment]
Any further thoughts on how fix this? I haven't had to time to dig into this yet myself.
Converting it to absolute just for the conf files at least sounds straightforward.
Some test would be nice. It seems to be a reoccurring issue.

**Comment by gesellix** [comment]
I didnt find any time, yet, but I agree that further changes should be backed by tests.

**Comment by tmortagne** [comment]
I propose the following: https://github.com/tcurdt/jdeb/commit/72c07fd689e227fd105ac80b52f1d2fda7a34298

**Comment by tcurdt** [comment]
Thanks for making progress here, @tmortagne 
@gesellix do you think that would work for you?

**Comment by gesellix** [comment]
@tcurdt @tmortagne I think that should work, or let's say: I should fix my jdeb usage if it doesn't work :)

**Comment by gesellix** [comment]
I can confirm that the [proposed change](https://github.com/tcurdt/jdeb/commit/72c07fd689e227fd105ac80b52f1d2fda7a34298) doesn't break any tests at [gesellix/gradle-debian-plugin](https://github.com/gesellix/gradle-debian-plugin). 👍

**Comment by tcurdt** [comment]
Sounds like it's time to get a release out then.

**Comment by tmortagne** [comment]
OK, merging the branch then.

**Comment by TomyLobo** [comment]
Has there been a release yet?
This issue prevents installing jdeb-created packages on the recently released Debian 11.
Our customers are currently switching to Debian 11 and this is a blocker.

**Comment by tcurdt** [comment]
I guess this issue can be closed.

I wasn't aware it was that critical. I'll try to get a release out in the next few days.

**Comment by tcurdt** [comment]
Well, I thought I just do it. So 1.10 is out :)
Just waiting for maven central to sync.

**Comment by TomyLobo** [comment]
It synced. The web UI has some caching I guess, but if you manipulate the URL, you can already see it in there, too:
https://search.maven.org/artifact/org.vafer/jdeb/1.10/maven-plugin
