### ISSUE TITLE
jdeb does not build/work on Java 7

### ISSUE THREAD

**Issue by tmortagne** [tcurdt/jdeb#365]
The configuration of the maven-compiler-plugin suggests that jdeb is supposed to support Java 7 but in practice it's not really usable with Java 7 because of some dependencies it's using: for example you immediately get an error when you try to build with Java 7 because of the ant dependency which requires Java 8 or more.

I'm not really suggesting fixing the dependencies to support Java 7 but more to make more official the fact that jdeb require Java 8 (i.e. increment the version in the maven-compiler-plugin configuration).

What do you think ?

**Comment by ebourg** [comment]
Let's move to Java 8 I think.

**Comment by tcurdt** [comment]
Since we have already implicitly made the switch in a previous release - do we really need to increment the major version? Thoughts?

**Comment by ebourg** [comment]
I don't think so, the 1.x line is fine.

**Comment by tcurdt** [comment]
just updated 1.7 -> 1.8
