### ISSUE TITLE
Some dependencies of Maven Plugins are expected to be in provided scope

### ISSUE THREAD

**Issue by tcurdt** [tcurdt/jdeb#475]
Building gives this error - that does not break the build:

```
Some dependencies of Maven Plugins are expected to be in provided scope.
Please make sure that dependencies listed below declared in POM
have set '<scope>provided</scope>' as well.

The following dependencies are in wrong scope:
 * org.apache.maven:maven-core:jar:3.6.0:compile
 * org.apache.maven:maven-model:jar:3.6.0:compile
 * org.apache.maven:maven-settings:jar:3.6.0:compile
 * org.apache.maven:maven-settings-builder:jar:3.6.0:compile
 * org.apache.maven:maven-builder-support:jar:3.6.0:compile
 * org.apache.maven:maven-repository-metadata:jar:3.6.0:compile
 * org.apache.maven:maven-artifact:jar:3.6.0:compile
 * org.apache.maven:maven-model-builder:jar:3.6.0:compile
 * org.apache.maven:maven-resolver-provider:jar:3.6.0:compile
 * org.apache.maven:maven-plugin-api:jar:3.6.0:compile
```
putting the deps into the requested scope does break the build though.

**Comment by tcurdt** [comment]
changing this from compile to provided breaks the integration tests

**Comment by VineelaKantamneni** [comment]
I'm getting exactly the same above error while building my code after updating my maven-plugin-plugin to the version 3.7.0.
But I don't have all the dependencies mentioned there in my pom.xml.
I've only **maven-plugin-api** in my pom.xml.
Can you please help me out to resolve this error.
thanks in advance

**Comment by tcurdt** [comment]
@VineelaKantamneni if I new how to resolve this the ticket would be closed ;)

**Comment by tcurdt** [comment]
we did some upgrades and this seems to be solved now.
