### ISSUE TITLE
Question: Build multiple deb packages when building a single module java project

### ISSUE THREAD

**Issue by alotia** [tcurdt/jdeb#553]
We have a single-module java project from which we are building a debian package. 
We would like to build two separate packages. The second package will contain different files (schema related), from the same project dir -- the idea being that this separate package will be deployed only occasionally.

Can someone please point out how I may go about doing this? I tried to "duplicate" the `<execution>` tag, but that doesn't build.

I guess if I have to, I can split this project into a multi-module project, but if I can just accomplish without having to do that, that would be better.

(Tried searching for it, but didn't find something pertinent. Also, I would have posted this on gitter, but noticed many times the devs weren't being notified of the post.)

Thanks for any info!

**Comment by ebourg** [comment]
It should work with multiple executions, could you show your plugin configuration in the pom?

**Comment by alotia** [comment]
@ebourg  Thank you for your reply. I was in the middle of trimming/cleaning the pom file to post here and noticed that the issue was on my side and I was not paying attention to the error! I had forgot to put a unique `<id>` in the two executions. (We didn't have one originally so it didn't occur to me to add one.) A quick test shows that it's working as expected. Closing this "issue". Cheers!
