### ISSUE TITLE
Maven: Commenting out timestamped has marked  snapshotExpand as Deprecated

### ISSUE THREAD

**Issue by guidoschreuder** [tcurdt/jdeb#558]
Since `timestamped` has been commented out the `@deprecated` "annotation" is now erroneously applied to the first parameter below it, which is `snapshotExpand`

https://github.com/tcurdt/jdeb/blame/ac0447fbc37dbfa1eff81dec686288a687b37644/src/main/java/org/vafer/jdeb/maven/DebMojo.java#L237

**Comment by tcurdt** [comment]
Urgh. Thanks for spotting this.

**Comment by tcurdt** [comment]
Thanks!
