### ISSUE TITLE
Where are the deb/control files located

### ISSUE THREAD

**Issue by ramanianushan** [tcurdt/jdeb#592]
Hi, I am trying to convert the source into a deb package and came across the below task.

When i am trying to run this on ubuntu, getting the error --> Data source not found : /home/ubuntu/amazon-kinesis-agent/src/main/resources/deb/data

how to resolve this error? Where we can get the source

 

<target name="package">
      <taskdef name="deb" classname="org.vafer.jdeb.ant.DebAntTask"/>
      <copy todir="${deb}/control">
        <fileset dir="src/main/resources/deb/control"/>
        <filterset begintoken="[[" endtoken="]]">
          <filter token="version" value="${version}"/>
          <filter token="name" value="${ant.project.name}"/>
        </filterset>
      </copy>
      <deb destfile="jdeb.deb" control="${deb}/control">
        <data src="src/main/resources/deb/data" type="directory">
          <exclude name="**/.svn"/>
        </data>
      </deb>
    </target>

**Comment by tcurdt** [comment]
Ant? Maven?
Did you have a look at the examples?
Or the docs?
What does your configuration look like?

You have to be a bit more specific for anyone to help you.

**Comment by ramanianushan** [comment]
Yes, its an ant build.. I am following the below documentation. Its not clear how to load the data files and control files that the task needs

https://github.com/tcurdt/jdeb/blob/master/docs/ant.md

**Comment by tcurdt** [comment]
Please check out the example

https://github.com/tcurdt/jdeb/blob/master/src/examples/ant/build.xml#L30

https://github.com/tcurdt/jdeb/blob/master/src/examples/ant/build.xml#L41

**Comment by ramanianushan** [comment]
Got it.. Thanks for providing the references... I made some progress.. This is the error i am getting now


Caused by: java.io.FileNotFoundException: /home/ubuntu/amazon-kinesis-agent/ant_build/deb/control/control (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at org.vafer.jdeb.ControlBuilder.createPackageControlFile(ControlBuilder.java:182)
        at org.vafer.jdeb.DebMaker.createSignedDeb(DebMaker.java:505)

**Comment by tcurdt** [comment]
No such file "/home/ubuntu/amazon-kinesis-agent/ant_build/deb/control/control"

https://github.com/tcurdt/jdeb/blob/09c0eeaccf9c90f857dbde27781fa9d8c0bdb87e/src/examples/ant/build.xml#L30
https://github.com/tcurdt/jdeb/blob/master/src/examples/ant/src/deb/control/control

**Comment by tcurdt** [comment]
If you got it to work please close the issue. Thanks!

**Comment by ramanianushan** [comment]
I copied the control file specified in the examples section to that directory and it started working.. it was able to succesfully create the deb file.  Thanks for all the help
