### ISSUE TITLE
[maven help wanted] integration tests are broken and disabled

### ISSUE THREAD

**Issue by tcurdt** [tcurdt/jdeb#625]
Newer java, newer maven, maven plugin, ant - the jdeb tests aren't the easiest to setup.
And now it the integration tests are broken.

The maven setups needs some love and I don't have the time to look into it.
For now I had to disabled the integration tests to not to block releases.

For this project to maintained longer it needs some love.
Especially if you are using it in a commercial setting please step up.
I've sustained the project for 17 years but I am not even really using it myself anymore.

It would be good to share the load.

**Comment by tmortagne** [comment]
I debugged it a little and ended up with https://github.com/tcurdt/jdeb/pull/626 (tested with Maven 3.9.6).

**Comment by tcurdt** [comment]
Thanks for the help!
