### ISSUE TITLE
deal with and fix some warnings and deprecations

### ISSUE THREAD

**Issue by tcurdt** [tcurdt/jdeb#628]
```
[WARNING] bootstrap class path not set in conjunction with -source 8
[WARNING] source value 8 is obsolete and will be removed in a future release
[WARNING] target value 8 is obsolete and will be removed in a future release
[WARNING] To suppress warnings about obsolete options, use -Xlint:-options.
[INFO] Annotation processing is enabled because one or more processors were found
  on the class path. A future release of javac may disable annotation processing
  unless at least one processor is specified by name (-processor), or a search
  path is specified (--processor-path, --processor-module-path), or annotation
  processing is enabled explicitly (-proc:only, -proc:full).
  Use -Xlint:-options to suppress this message.
  Use -proc:none to disable annotation processing.
[INFO] /Users/tcurdt/Projects/jdeb/src/main/java/org/vafer/jdeb/utils/OutputTimestampResolver.java: Some input files use or override a deprecated API.
[INFO] /Users/tcurdt/Projects/jdeb/src/main/java/org/vafer/jdeb/utils/OutputTimestampResolver.java: Recompile with -Xlint:deprecation for details.
[INFO] /Users/tcurdt/Projects/jdeb/src/main/java/org/vafer/jdeb/maven/DebMojo.java: /Users/tcurdt/Projects/jdeb/src/main/java/org/vafer/jdeb/maven/DebMojo.java uses unchecked or unsafe operations.
[INFO] /Users/tcurdt/Projects/jdeb/src/main/java/org/vafer/jdeb/maven/DebMojo.java: Recompile with -Xlint:unchecked for details.
```

**Comment by jasontrademarked** [comment]
use grudle. Apply Java as a backup lang for def

**Comment by tcurdt** [comment]
> use grudle. Apply Java as a backup lang for def

I am not following.

**Comment by JuniorTheCoder** [comment]
To address this, you can explicitly set the bootstrap classpath using the -bootclasspath option in your compilation command or Maven configuration. Ensure that the bootstrap classpath points to the appropriate JDK version you are targeting.

Update your source compatibility to a newer version (e.g., 11, 17) to avoid this warning.

Update your target bytecode version to a newer one (e.g., 11, 17) to avoid this warning.

You can add -Xlint:-options to your compilation command or Maven configuration to suppress these warnings.

Review the deprecated API usage in the mentioned file and update it to use non-deprecated alternatives.

Review the code in DebMojo.java and ensure that it is type-safe. Consider using generics or appropriate type checks to address this warning.

Recompile your code with -Xlint:deprecation to get more insights into the deprecated API usage and address them accordingly.

Recompile your code with -Xlint:unchecked to get more insights into the unchecked or unsafe operations and address them accordingly.

**Comment by tcurdt** [comment]
@JuniorTheCoder That sounds like ChatGPT.

The help needed is a PR with a working maven build - without the warnings.

**Comment by Jcls100** [comment]
> ```
> [WARNING] bootstrap class path not set in conjunction with -source 8
> [WARNING] source value 8 is obsolete and will be removed in a future release
> [WARNING] target value 8 is obsolete and will be removed in a future release
> [WARNING] To suppress warnings about obsolete options, use -Xlint:-options.
> [INFO] Annotation processing is enabled because one or more processors were found
>   on the class path. A future release of javac may disable annotation processing
>   unless at least one processor is specified by name (-processor), or a search
>   path is specified (--processor-path, --processor-module-path), or annotation
>   processing is enabled explicitly (-proc:only, -proc:full).
>   Use -Xlint:-options to suppress this message.
>   Use -proc:none to disable annotation processing.
> [INFO] /Users/tcurdt/Projects/jdeb/src/main/java/org/vafer/jdeb/utils/OutputTimestampResolver.java: Some input files use or override a deprecated API.
> [INFO] /Users/tcurdt/Projects/jdeb/src/main/java/org/vafer/jdeb/utils/OutputTimestampResolver.java: Recompile with -Xlint:deprecation for details.
> [INFO] /Users/tcurdt/Projects/jdeb/src/main/java/org/vafer/jdeb/maven/DebMojo.java: /Users/tcurdt/Projects/jdeb/src/main/java/org/vafer/jdeb/maven/DebMojo.java uses unchecked or unsafe operations.
> [INFO] /Users/tcurdt/Projects/jdeb/src/main/java/org/vafer/jdeb/maven/DebMojo.java: Recompile with -Xlint:unchecked for details.
> ```

**Comment by Dancan1471** [comment]
> ```
> [WARNING] bootstrap class path not set in conjunction with -source 8
> [WARNING] source value 8 is obsolete and will be removed in a future release
> [WARNING] target value 8 is obsolete and will be removed in a future release
> [WARNING] To suppress warnings about obsolete options, use -Xlint:-options.
> [INFO] Annotation processing is enabled because one or more processors were found
>   on the class path. A future release of javac may disable annotation processing
>   unless at least one processor is specified by name (-processor), or a search
>   path is specified (--processor-path, --processor-module-path), or annotation
>   processing is enabled explicitly (-proc:only, -proc:full).
>   Use -Xlint:-options to suppress this message.
>   Use -proc:none to disable annotation processing.
> [INFO] /Users/tcurdt/Projects/jdeb/src/main/java/org/vafer/jdeb/utils/OutputTimestampResolver.java: Some input files use or override a deprecated API.
> [INFO] /Users/tcurdt/Projects/jdeb/src/main/java/org/vafer/jdeb/utils/OutputTimestampResolver.java: Recompile with -Xlint:deprecation for details.
> [INFO] /Users/tcurdt/Projects/jdeb/src/main/java/org/vafer/jdeb/maven/DebMojo.java: /Users/tcurdt/Projects/jdeb/src/main/java/org/vafer/jdeb/maven/DebMojo.java uses unchecked or unsafe operations.
> [INFO] /Users/tcurdt/Projects/jdeb/src/main/java/org/vafer/jdeb/maven/DebMojo.java: Recompile with -Xlint:unchecked for details.
> ```

Reinstall it and it will work fine

**Comment by Dancan1471** [comment]
REINSTALL

**Comment by arunsak04** [comment]
Okay, if it will work fine by reinstalling then you can close the issue

**Comment by tcurdt** [comment]
"reinstall" is not a fix.

**Comment by tcurdt** [comment]
@inglepriyanka148867 Please don't use AI to comment.
The issues needs to be fixed - not explained.

**Comment by Erwin-Ny** [comment]
Update the compiler

**Comment by As90909w** [comment]
so update ASDD file is active now? As I mean the compiler is computing properly?

**Comment by tcurdt** [comment]
should be fixed
