### ISSUE TITLE
GitHub page

### ISSUE THREAD

**Issue by aflacake** [tcurdt/jdeb#680]
Blank page at http://tcurdt.github.io/jdeb. I'm using Chrome, solution?

**Comment by tcurdt** [comment]
That's weird. Thanks for reporting.
Seems like a redirect is missing.

The links from the README seem to work though. Tried those?

Javadocs are here https://tcurdt.github.io/jdeb/release/1.10/apidocs/
Xref is here https://tcurdt.github.io/jdeb/release/1.10/xref/

**Comment by tcurdt** [comment]
Fixed. Thanks!
