### ISSUE TITLE
.changes file is not reproducible

### ISSUE THREAD

**Issue by ebourg** [tcurdt/jdeb#712]
`ChangesFileBuilder` doesn't use the `outputTimestamp` parameter to set the value of the `Date` field. This makes the `.changes` files not reproducible.

**Comment by Sarun2515** [comment]
> `ChangesFileBuilder`ไม่ใช้`outputTimestamp`พารามิเตอร์ในการตั้งค่าของ`Date`ฟิลด์ ซึ่งทำให้`.changes`ไม่สามารถทำซ้ำไฟล์ได้

**Comment by norrisjeremy** [comment]
Hi @tcurdt,

Please see #748 for my proposed fix for this.

Thanks,
Jeremy

**Comment by tcurdt** [comment]
Seems like @norrisjeremy is on fire :) Thanks!

Since this is your issue, can you review it @ebourg ?

**Comment by Sardar9292** [comment]
عالی

**Comment by norrisjeremy** [comment]
@tcurdt When can you land this change and then publish a new release to Maven Central?

**Comment by tcurdt** [comment]
I was hoping for @ebourg to have a look - but if he is too busy I will have a look the next few days.

**Comment by tcurdt** [comment]
This is merged now. I'll see if I can get a release out next week.

**Comment by norrisjeremy** [comment]
Hi @tcurdt,

Any news on when a new release can be pushed to Maven Central?

Thanks,
Jeremy

**Comment by tcurdt** [comment]
Sorry, didn't get around to it yet. Scheduled for the 22nd.

**Comment by tcurdt** [comment]
0.12 is released, @norrisjeremy 
Maven Central still needs to sync.
Thanks for the help.
